package filter_test

import (
	"testing"

	"github.com/yavosh/gocoder/internal/extractor"
	"github.com/yavosh/gocoder/internal/filter"
)

func TestIsGenerated(t *testing.T) {
	tests := []struct {
		name     string
		body     string
		expected bool
	}{
		{"protobuf", "// Code generated by protoc-gen-go. DO NOT EDIT.\nfunc Foo() {}", true},
		{"mockgen", "// Code generated by MockGen. DO NOT EDIT.\nfunc Foo() {}", true},
		{"normal", "// HandleRequest processes a request.\nfunc HandleRequest() {}", false},
		{"wire", "//go:generate wire\nfunc Foo() {}", true},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			f := extractor.ExtractedFunc{Body: tt.body}
			if got := filter.IsGenerated(f); got != tt.expected {
				t.Errorf("IsGenerated(%q) = %v, want %v", tt.name, got, tt.expected)
			}
		})
	}
}

func TestDedup(t *testing.T) {
	funcs := []extractor.ExtractedFunc{
		{Name: "Foo", Body: "func Foo() { return 1 }"},
		{Name: "Foo", Body: "func Foo() { return 1 }"},
		{Name: "Bar", Body: "func Bar() { return 2 }"},
	}

	deduped := filter.Dedup(funcs)
	if len(deduped) != 2 {
		t.Errorf("expected 2 after dedup, got %d", len(deduped))
	}
}

func TestMinLines(t *testing.T) {
	short := extractor.ExtractedFunc{Body: "func F() {}"}
	long := extractor.ExtractedFunc{Body: "func F() {\n\ta := 1\n\tb := 2\n\tc := 3\n\treturn a + b + c\n}"}

	if filter.HasMinLines(short, 3) {
		t.Error("expected short function to fail min lines check")
	}
	if !filter.HasMinLines(long, 3) {
		t.Error("expected long function to pass min lines check")
	}
}

func TestFilterAll(t *testing.T) {
	funcs := []extractor.ExtractedFunc{
		{Name: "Generated", Body: "// Code generated by mockgen. DO NOT EDIT.\nfunc Generated() {}"},
		{Name: "Short", Body: "func Short() {}"},
		{Name: "Good", Body: "func Good() {\n\ta := 1\n\tb := 2\n\treturn a + b\n}"},
		{Name: "Good", Body: "func Good() {\n\ta := 1\n\tb := 2\n\treturn a + b\n}"}, // duplicate
		{Name: "AlsoGood", Body: "func AlsoGood() {\n\tx := 1\n\ty := 2\n\treturn x + y\n}"},
	}

	result := filter.FilterAll(funcs, 3)
	if len(result) != 2 {
		t.Errorf("expected 2 after FilterAll, got %d", len(result))
	}
}
