package extractor_test

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/yavosh/gocoder/internal/extractor"
)

const testGoFile = `package server

import (
	"context"
	"fmt"
)

// HandleRequest processes an incoming request and returns an error
// if validation fails.
func (s *Server) HandleRequest(ctx context.Context, req *Request) error {
	if err := s.validate(req); err != nil {
		return fmt.Errorf("validation: %w", err)
	}
	return nil
}

// NewServer creates a new Server with the given config.
func NewServer(cfg Config) *Server {
	return &Server{cfg: cfg}
}
`

func TestExtractFunctions(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "server.go")
	if err := os.WriteFile(path, []byte(testGoFile), 0o644); err != nil {
		t.Fatal(err)
	}

	funcs, err := extractor.ExtractFunctions(path)
	if err != nil {
		t.Fatalf("ExtractFunctions: %v", err)
	}

	if len(funcs) != 2 {
		t.Fatalf("expected 2 functions, got %d", len(funcs))
	}

	hr := funcs[0]
	if hr.Name != "HandleRequest" {
		t.Errorf("expected name HandleRequest, got %q", hr.Name)
	}
	if hr.Receiver != "*Server" {
		t.Errorf("expected receiver *Server, got %q", hr.Receiver)
	}
	if hr.Doc == "" {
		t.Error("expected doc comment, got empty")
	}
	if hr.Package != "server" {
		t.Errorf("expected package server, got %q", hr.Package)
	}

	ns := funcs[1]
	if ns.Name != "NewServer" {
		t.Errorf("expected name NewServer, got %q", ns.Name)
	}
	if ns.Receiver != "" {
		t.Errorf("expected no receiver, got %q", ns.Receiver)
	}
}

func TestExtractFunctionsSkipsGenerated(t *testing.T) {
	dir := t.TempDir()
	content := "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage pb\n\nfunc Foo() {}\n"
	path := filepath.Join(dir, "gen.pb.go")
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}

	funcs, err := extractor.ExtractFunctions(path)
	if err != nil {
		t.Fatalf("ExtractFunctions: %v", err)
	}
	if len(funcs) != 0 {
		t.Errorf("expected 0 functions from generated file, got %d", len(funcs))
	}
}
